name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: aleskucera/private-repo

    - name: Set up Git
      run: |
        git config --global user.name 'Aleš Kučera'
        git config --global user.email 'kuceral4@fel.cvut.cz'

    - name: Authenticate with GitHub Token
      run: echo "${{ secrets.PUBLIC_REPO_TOKEN }}"  # Debug: Ensure token is available
      shell: bash

    - name: Add public repo remote
      run: |
        git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/aleskucera/public-repo.git
        git remote -v  # Debug: List remotes

    - name: Debug remote access
      run: |
        git ls-remote public  # Debug: Check remote access
 

    - name: Push to public repo
      run: |
        git push public main --force

