name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v3
      with:
        repository: aleskucera/private-repo
        token: ${{ secrets.PUBLIC_REPO_TOKEN }}

    - name: Add public repo remote
      run: |
        git remote add public https://github.com/aleskucera/public-repo.git
        git remote -v  # Debug: List remotes
    
    - name: Force push to public repo
      run: |
        git push public main --force
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}

 

